{
 "title": "4 Golden Signals",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Exporter status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "request_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(error_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "CPU %"
    },
    {
     "expr": "process_resident_memory_bytes / process_virtual_memory_bytes * 100",
     "legendFormat": "Memory %"
    },
    {
     "expr": "process_open_fds / process_max_fds * 100",
     "legendFormat": "FD %"
    },
    { "expr": "active_requests", "legendFormat": "Active Requests" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_count_total{endpoint=\"/400\"}[5m]))\n/\nsum(rate(request_count_total[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}